name: flutter_application_1
description: "Sopa de letras realizado por Keiner Frontado y Mansour Ortega"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # SDK mínimo de tu app
  # Opcional: Para iconos adaptativos en Android (Android 8.0+)
  adaptive_icon_background: "#76c984" # Color de fondo
